// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main service bound to the UI. Pure facade over engines;
 * all engine state is per-project, namespaced by Project.ID.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as acp$0 from "./acp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentstore$0 from "./agentstore/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as editor$0 from "./editor/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "./git/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lsp$0 from "./lsp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "./project/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as search$0 from "./search/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "./settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ACPClearTranscript deletes the session displayed by the caller. It refuses
 * while a harness is running or starting on that session, since deleting the
 * record would strand the harness's writes.
 */
export function ACPClearTranscript(projectID: string, sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2240702008, projectID, sessionID);
}

/**
 * ACPDeleteSession removes a persisted session. Refuses while a running
 * harness is writing to it; afterwards a dead stub's dangling chatID is
 * cleared so the next spawn mints a fresh record.
 */
export function ACPDeleteSession(projectID: string, sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3198438054, projectID, sessionID);
}

/**
 * ACPHarnesses lists known agent profiles with PATH availability.
 */
export function ACPHarnesses(): $CancellablePromise<acp$0.Info[] | null> {
    return $Call.ByID(184583539);
}

/**
 * ACPLoadTranscript returns the persisted entries for the project's active
 * (or latest) session.
 */
export function ACPLoadTranscript(projectID: string): $CancellablePromise<$models.AgentTranscript> {
    return $Call.ByID(1274648703, projectID);
}

/**
 * ACPNewSession closes the current harness connection and spawns a fresh
 * session with the same harness. The transcript is kept; a divider note entry
 * marks the boundary.
 * 
 * Get + close + spawn are serialized under a.mu together with claimStart, so a
 * concurrent ACPStart / ACPStop cannot interleave: the closed session is never
 * resurrected by a stale-closed send, and only one spawn is in flight.
 */
export function ACPNewSession(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(1143976027, projectID);
}

/**
 * ACPOpenSession switches the UI/harness context to a persisted session:
 * with a running harness it re-points the transcript and re-emits it; without
 * one it just emits the stored transcript (no auto-start).
 */
export function ACPOpenSession(projectID: string, sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(4234377075, projectID, sessionID);
}

/**
 * ACPRenameSession sets a session's display title.
 */
export function ACPRenameSession(sessionID: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(4197558245, sessionID, title);
}

/**
 * ACPRespondPermission resolves a pending permission request: optionId picks
 * one of the offered options; cancel=true answers {"outcome":"cancelled"}.
 */
export function ACPRespondPermission(projectID: string, requestID: string, optionID: string, cancel: boolean): $CancellablePromise<void> {
    return $Call.ByID(2968285233, projectID, requestID, optionID, cancel);
}

/**
 * ACPSendPrompt runs one synchronous prompt turn: the user entry is persisted
 * and emitted up front, session/update notifications stream out as acp.msg /
 * acp.tool events while the turn is open, and the assembled agent reply is
 * persisted once the turn completes.
 */
export function ACPSendPrompt(projectID: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(2328941885, projectID, text);
}

/**
 * ACPSessions lists the project's persisted agent sessions (newest first).
 */
export function ACPSessions(projectID: string): $CancellablePromise<agentstore$0.SessionMeta[] | null> {
    return $Call.ByID(157939588, projectID);
}

/**
 * ACPStart resolves the harness profile and spawns one ACP session for the
 * project (one session/connection MVP). After start the persisted transcript
 * is emitted (acp.transcript) followed by an idle state.
 */
export function ACPStart(projectID: string, harnessName: string): $CancellablePromise<void> {
    return $Call.ByID(4292634007, projectID, harnessName);
}

/**
 * ACPStop closes the harness connection (terminating the child process) and
 * reports harness-down.
 */
export function ACPStop(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(3127032957, projectID);
}

/**
 * BufferClose releases a closed tab's snapshot; switching projects does not
 * close buffers. The ID prevents a late close from removing a reopened tab.
 */
export function BufferClose(projectID: string, path: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(1656880807, projectID, path, id);
}

/**
 * BufferRead returns the project's open text buffer, reading disk only on
 * first open. Like ReadFile, paths may refer to definitions outside the root.
 */
export function BufferRead(projectID: string, path: string): $CancellablePromise<editor$0.Buffer> {
    return $Call.ByID(753238473, projectID, path);
}

/**
 * BufferUpdate retains a text tab's latest snapshot in memory. The frontend
 * advances Version for edits, saves and explicit reloads.
 */
export function BufferUpdate(projectID: string, path: string, buffer: editor$0.Buffer): $CancellablePromise<void> {
    return $Call.ByID(1677947720, projectID, path, buffer);
}

/**
 * CloseWatcher stops and releases the watcher for projectID and marks the
 * project closed so the forwarder suppresses any buffered events.
 */
export function CloseWatcher(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(4067835283, projectID);
}

/**
 * CloseWelcome hides the welcome window after a project has been opened.
 */
export function CloseWelcome(): $CancellablePromise<void> {
    return $Call.ByID(3845525055);
}

/**
 * CreateFile creates an empty file at path, creating parent directories as
 * needed. Fails when the file already exists.
 */
export function CreateFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(1457150717, path);
}

/**
 * CreateFolder creates the directory at path (including parents). Fails when
 * the directory already exists.
 */
export function CreateFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(1104706407, path);
}

/**
 * DeletePath removes the file or directory tree at path. The project root
 * itself is never deletable.
 */
export function DeletePath(path: string): $CancellablePromise<void> {
    return $Call.ByID(415982615, path);
}

/**
 * EnsureWorkspaceWindow opens the workspace window if none exists (or shows
 * the existing one). Called by the frontend after opening a project.
 */
export function EnsureWorkspaceWindow(): $CancellablePromise<void> {
    return $Call.ByID(2804870294);
}

/**
 * ForgetRecent drops a recents entry by root path.
 */
export function ForgetRecent(root: string): $CancellablePromise<void> {
    return $Call.ByID(2380934393, root);
}

/**
 * GitAheadBehind reports the ahead/behind counts versus the remote-tracking
 * branch of HEAD. Remote is always "origin" (MVP); a missing upstream or
 * absent tracking ref yields Remote "" with zeros instead of an error.
 */
export function GitAheadBehind(projectID: string): $CancellablePromise<$models.GitSyncInfo> {
    return $Call.ByID(3944216894, projectID);
}

/**
 * GitBranches lists local branches (refs/heads, sorted, short names).
 */
export function GitBranches(projectID: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(991782069, projectID);
}

/**
 * GitCheckout switches worktree to the given local branch.
 */
export function GitCheckout(projectID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2829352117, projectID, name);
}

/**
 * GitCommit commits staged changes with the fixed "codesaber <codesaber@local>" identity.
 */
export function GitCommit(projectID: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(510842760, projectID, message);
}

/**
 * GitCreateBranch creates a branch pointing at the current HEAD.
 */
export function GitCreateBranch(projectID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(463711033, projectID, name);
}

/**
 * GitDiff returns the diff for path against HEAD (staged) or the index (unstaged).
 */
export function GitDiff(projectID: string, path: string, staged: boolean): $CancellablePromise<git$0.DiffPatch> {
    return $Call.ByID(1092919998, projectID, path, staged);
}

/**
 * GitFetch fetches all configured remotes (30s timeout, no auth MVP).
 */
export function GitFetch(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(4171313407, projectID);
}

/**
 * GitLog returns the n most recent commit entries walking first-parent from HEAD.
 */
export function GitLog(projectID: string, n: number): $CancellablePromise<git$0.LogEntry[] | null> {
    return $Call.ByID(635439101, projectID, n);
}

/**
 * GitPush pushes HEAD to the first remote with its default refspec (MVP: no auth).
 */
export function GitPush(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(3700652753, projectID);
}

/**
 * GitStage adds files to the index ("add"; deleted files are recorded via "rm").
 */
export function GitStage(projectID: string, paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2828503865, projectID, paths);
}

/**
 * GitStageHunks stages selected hunks (0-based indices into the file's
 * unified diff) via the git binary. Requires `git` on PATH; otherwise it
 * fails fast with a clear availability error.
 */
export function GitStageHunks(projectID: string, path: string, hunkIdx: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(3083290090, projectID, path, hunkIdx);
}

/**
 * GitStats computes on-demand per-file [additions, deletions]; capped at
 * maxStatsFiles paths per call to keep it cheap.
 */
export function GitStats(projectID: string, paths: string[] | null, staged: boolean): $CancellablePromise<{ [_ in string]?: number[] } | null> {
    return $Call.ByID(2998795984, projectID, paths, staged);
}

/**
 * GitStatus returns Staged/Unstaged/Untracked changes plus the current branch.
 */
export function GitStatus(projectID: string): $CancellablePromise<git$0.Status> {
    return $Call.ByID(69657891, projectID);
}

/**
 * GitUnstage resets paths back out of the index.
 */
export function GitUnstage(projectID: string, paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3401256016, projectID, paths);
}

/**
 * GitUnstageHunks reverts selected staged hunks (0-based indices into the
 * file's staged diff) out of the index via the git binary.
 */
export function GitUnstageHunks(projectID: string, path: string, hunkIdx: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(3011232361, projectID, path, hunkIdx);
}

/**
 * HealthMetrics computes cheap per-call counters at the 1Hz poll rate the
 * Perf HUD uses. RSS via go-osstat/memory (pure Go, no cgo); on failure the
 * field simply stays 0 rather than blocking the rest of the snapshot.
 */
export function HealthMetrics(): $CancellablePromise<$models.Health> {
    return $Call.ByID(2849428982);
}

/**
 * IndexFiles returns all file paths under root (absolute), walking the full
 * tree recursively. Skips .git, node_modules, dist, build, vendor, target and
 * .next directories, plus all other dotfiles; capped at maxIndexFiles.
 * Phase 6 (tree-sitter index) replaces this walk.
 */
export function IndexFiles(root: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1720977940, root);
}

/**
 * LSPDefinition resolves Go-to-definition at a position; result URIs are
 * translated back into absolute filesystem paths for the frontend.
 */
export function LSPDefinition(projectID: string, path: string, line: number, col: number): $CancellablePromise<lsp$0.Location[] | null> {
    return $Call.ByID(13863991, projectID, path, line, col);
}

/**
 * LSPDidChange sends the full document content at the new version.
 */
export function LSPDidChange(projectID: string, path: string, version: number, content: string): $CancellablePromise<void> {
    return $Call.ByID(2034184663, projectID, path, version, content);
}

/**
 * LSPDidClose tells gopls the document is no longer open; no-op when the
 * server is not running (never spawns one for a close).
 */
export function LSPDidClose(projectID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(4019370121, projectID, path);
}

/**
 * LSPDidOpen notifies gopls of an opened document (full text sync).
 */
export function LSPDidOpen(projectID: string, path: string, version: number, content: string): $CancellablePromise<void> {
    return $Call.ByID(3726768607, projectID, path, version, content);
}

/**
 * LSPDidSave signals a save ("includeText" style with the saved content
 * handled by the caller passing text; empty text means notify-only).
 */
export function LSPDidSave(projectID: string, path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3829721934, projectID, path, content);
}

/**
 * LSPEnsure explicitly starts the project's gopls (state reporting happens
 * inside ensureLSP). Guests call it on opening the first .go tab; startup is
 * otherwise lazy via LSPDidOpen.
 */
export function LSPEnsure(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(1659219864, projectID);
}

/**
 * LSPHover resolves hover markdown-ish content at a position (nil = none).
 */
export function LSPHover(projectID: string, path: string, line: number, col: number): $CancellablePromise<lsp$0.Hover | null> {
    return $Call.ByID(54469424, projectID, path, line, col);
}

/**
 * LSPSymbols returns hierarchical document symbols for the file.
 */
export function LSPSymbols(projectID: string, path: string): $CancellablePromise<lsp$0.DocumentSymbol[] | null> {
    return $Call.ByID(408951487, projectID, path);
}

/**
 * ListProjects returns currently open projects, most recently used first.
 */
export function ListProjects(): $CancellablePromise<project$0.Project[] | null> {
    return $Call.ByID(3918706113);
}

/**
 * ListTree walks root recursively to maxTreeDepth, dirs-first sorted, skipping
 * dotfiles except .env, .gitignore and .github.
 */
export function ListTree(root: string): $CancellablePromise<$models.Entry[] | null> {
    return $Call.ByID(1531066199, root);
}

/**
 * OpenProject registers the project, remembers it in recents, starts a
 * filesystem watcher and emits "project.added". Watcher events are re-emitted
 * as "fs.change" with {projectId, path, op}.
 */
export function OpenProject(root: string): $CancellablePromise<project$0.Project> {
    return $Call.ByID(542099676, root);
}

/**
 * PasteInto writes the items into target directory dir. File/folder items
 * are copied recursively; image items are written as screenshot-<ts>.png.
 * Refuses targets outside open project roots.
 */
export function PasteInto(dir: string, items: $models.PasteItem[] | null): $CancellablePromise<void> {
    return $Call.ByID(35969440, dir, items);
}

/**
 * PasteboardRead returns the pasteboard contents as pasteable items: copied
 * files/folders (Source = absolute path) or a screenshot image (DataB64 =
 * PNG). An empty result means nothing pasteable is on the pasteboard.
 */
export function PasteboardRead(): $CancellablePromise<$models.PasteItem[] | null> {
    return $Call.ByID(3195205198);
}

/**
 * PickFolder opens a native folder-picker and returns the chosen absolute
 * path, or an empty string if the user cancelled the dialog.
 */
export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(661057334);
}

/**
 * ReadFile returns file content, refusing files larger than maxFileSize.
 */
export function ReadFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(1742541433, path);
}

/**
 * ReadFileB64 returns binary file content base64-encoded, for image previews.
 * Refuses files larger than maxFileSize.
 */
export function ReadFileB64(path: string): $CancellablePromise<string> {
    return $Call.ByID(4234968659, path);
}

/**
 * RecentProjects returns the persisted recents list.
 */
export function RecentProjects(): $CancellablePromise<project$0.Recent[] | null> {
    return $Call.ByID(769741074);
}

/**
 * RemoveProject closes the project: registry removal, LSP shutdown, watcher
 * shutdown and "project.removed" emission. LSP-stop failure never aborts the
 * remaining cleanup steps — the project is going away either way.
 */
export function RemoveProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(4208626588, id);
}

/**
 * RevealInFinder shows path in the OS file manager (Finder on macOS),
 * selecting it when possible.
 */
export function RevealInFinder(path: string): $CancellablePromise<void> {
    return $Call.ByID(291909345, path);
}

/**
 * SaveFile persists content via editor.Service (atomic write + dirty tracking).
 */
export function SaveFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(2606141320, path, content);
}

/**
 * SearchText runs a project-wide text search and returns the full result
 * synchronously (MVP: no streaming; a new call for the same project cancels
 * the previous one, and the frontend drops superseded responses by seq).
 */
export function SearchText(projectID: string, term: string, regex: boolean, caseSensitive: boolean, include: string, exclude: string): $CancellablePromise<search$0.Result> {
    return $Call.ByID(3252556316, projectID, term, regex, caseSensitive, include, exclude);
}

/**
 * SettingsGet returns the persisted global settings (defaults when no file
 * exists yet).
 */
export function SettingsGet(): $CancellablePromise<settings$0.Model> {
    return $Call.ByID(3395415274);
}

/**
 * SettingsPut sanitizes and persists the settings document. Invalid values
 * are corrected (font size clamped, garbage accent color dropped) or kept
 * with a warning (unknown shell path) — Put never fails on user input, only
 * on I/O errors. MVP note: no settings.updated broadcast; a single workspace
 * window is assumed, so cross-window sync is out of scope for now.
 */
export function SettingsPut(m: settings$0.Model): $CancellablePromise<void> {
    return $Call.ByID(426256923, m);
}

/**
 * TermInput writes raw bytes to the terminal's stdin.
 */
export function TermInput(termID: string, data: string | null): $CancellablePromise<void> {
    return $Call.ByID(384163063, termID, data);
}

/**
 * TermResize resizes the terminal's PTY window.
 */
export function TermResize(termID: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(2431331613, termID, rows, cols);
}

/**
 * TermStart spawns a shell session inside a PTY for the project and returns
 * its termID ("projectId|suffix"). shell is the binary to run ("" defaults
 * to /bin/sh); cwd is the project root.
 */
export function TermStart(projectID: string, shell: string, suffix: string): $CancellablePromise<string> {
    return $Call.ByID(1516469139, projectID, shell, suffix);
}

/**
 * TermStop terminates and releases the terminal session.
 */
export function TermStop(termID: string): $CancellablePromise<void> {
    return $Call.ByID(3987172193, termID);
}
