// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agentstore$0 from "./agentstore/models.js";

/**
 * AgentTranscript pairs persisted entries with the session they belong to.
 */
export interface AgentTranscript {
    "sessionID": string;
    "entries": agentstore$0.Entry[] | null;
}

/**
 * Entry is a node in a project tree listing. Path is absolute.
 */
export interface Entry {
    "name": string;
    "path": string;
    "dir": boolean;
}

/**
 * GitSyncInfo is the ahead/behind sync state relative to a remote.
 */
export interface GitSyncInfo {
    "remote": string;
    "branch": string;
    "ahead": number;
    "behind": number;
}

/**
 * Health is a live snapshot of IDE backend health for the Perf HUD overlay.
 */
export interface Health {
    "rssMB": number;
    "goroutines": number;
    "terminals": number;
    "watchers": number;
    "acpSessions": number;
    "editorBuffers": number;
    "worktreesSize": string;
}

/**
 * PasteItem is one entry read from the pasteboard: either a file/folder
 * reference (dataB64 empty, Source set) or inline image data (screenshots;
 * Source empty, dataB64 holds the PNG bytes).
 */
export interface PasteItem {
    "name": string;
    "isDir": boolean;
    "source": string;
    "dataB64"?: string;
}
