// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    Diagnostic,
    Info,
    ModelOption,
    ModelState
} from "./models.js";
