// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Diagnostic {
    "ready": boolean;
    "code": string;
    "message": string;
    "warnings": string[] | null;
    "model": string;
}

/**
 * Info describes one launchable ACP agent profile.
 */
export interface Info {
    "name": string;
    "command": string[] | null;
    "available": boolean;
    "managed": boolean;
    "version": string;
    "isolated": boolean;
}

export interface ModelOption {
    "id": string;
    "name": string;
    "description": string;
    "group": string;
}

export interface ModelState {
    "sessionId": string;
    "currentId": string;
    "options": ModelOption[] | null;
}
