// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Model is the full settings document. Zero values mean "default":
 * EditorFontSizePx 0 renders as 13px and AccentColor "" renders as
 * #4a5bfc (the :root CSS defaults).
 */
export interface Model {
    "bracketColors": boolean;
    "minimap": boolean;

    /**
     * "" = platform default
     */
    "terminalShell": string;

    /**
     * 0 = 13
     */
    "editorFontSizePx"?: number;
    "searchIncludeGlobs": string;

    /**
     * hex, "" default #4a5bfc
     */
    "accentColor"?: string;
    "perfHud"?: boolean;
    "vimMode"?: boolean;
}
