// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Change {
    "path": string;
    "status": ChangeStatus;
    "size"?: number;
}

export enum ChangeStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ChangeAdded = 65,
    ChangeModified = 77,
    ChangeDeleted = 68,
    ChangeUntracked = 85,
};

export interface DiffHunk {
    "header": string;
    "lines": string[] | null;
    "additions": number;
    "deletions": number;
}

export interface DiffPatch {
    "oldPath": string;
    "newPath": string;
    "hunks": DiffHunk[] | null;
}

export interface LogEntry {
    "hash": string;
    "author": string;
    "message": string;
    "time": string;
}

export interface Status {
    "branch": string;
    "head": string;
    "staged": Change[] | null;
    "unstaged": Change[] | null;
    "untracked": Change[] | null;
}
